analyzers:
  hercules:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Hercules A200
    find_and_remove_prefix: 'hercules_base: '
    expected: ['hercules_base: power_status','hercules_base: system_status','hercules_base: safety_status','hercules_base: software_status']
    timeout: 5.0
